#!/bin/bash
# generate-agents-review.sh
# Generates a comprehensive review report for agents.md

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Check if agents.md exists
AGENTS_FILE=".cursor/agents.md"

if [ ! -f "$AGENTS_FILE" ]; then
    echo -e "${RED}Error: agents.md not found: $AGENTS_FILE${NC}"
    echo "Initialize project first with: /init-project"
    exit 1
fi

# Get current date
CURRENT_DATE=$(date +%Y-%m-%d)
REVIEW_FILE=".cursor/agents-review-${CURRENT_DATE}.md"

echo -e "${BLUE}📊 Generating agents.md review report...${NC}"
echo ""

# Count learnings (sections with "Added:" date)
LEARNING_COUNT=$(grep -c "Added:" "$AGENTS_FILE" || echo "0")

# Count by category
ARCHITECTURE_COUNT=$(grep -c "^## Architecture\|^###.*Architecture" "$AGENTS_FILE" || echo "0")
MISTAKES_COUNT=$(grep -c "^## Common Mistakes\|^### Don't" "$AGENTS_FILE" || echo "0")
STANDARDS_COUNT=$(grep -c "^## Code Standards\|^###.*Standard" "$AGENTS_FILE" || echo "0")

# Get last updated date
LAST_UPDATED=$(grep "Last Updated\|Last updated" "$AGENTS_FILE" | head -1 | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}" || echo "Unknown")

# Count entries with dates
ENTRIES_WITH_DATES=$(grep -c "Added:.*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}" "$AGENTS_FILE" || echo "0")

# Find most recent addition
MOST_RECENT=$(grep "Added:" "$AGENTS_FILE" | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}" | sort -r | head -1 || echo "None")

# Create review report
cat > "$REVIEW_FILE" << EOF
# agents.md Review Report

**Date**: ${CURRENT_DATE}  
**Last Updated**: ${LAST_UPDATED}  
**Most Recent Addition**: ${MOST_RECENT}

---

## Summary

- **Total Learnings**: ${LEARNING_COUNT}
- **Architecture Principles**: ${ARCHITECTURE_COUNT}
- **Common Mistakes**: ${MISTAKES_COUNT}
- **Code Standards**: ${STANDARDS_COUNT}
- **Entries with Dates**: ${ENTRIES_WITH_DATES}

---

## File Statistics

\`\`\`
File: ${AGENTS_FILE}
Size: $(wc -l < "$AGENTS_FILE" | tr -d ' ') lines
Last Modified: $(stat -f "%Sm" "$AGENTS_FILE" 2>/dev/null || stat -c "%y" "$AGENTS_FILE" 2>/dev/null || echo "Unknown")
\`\`\`

---

## Content Analysis

### Learning Entries by Date

$(grep "Added:" "$AGENTS_FILE" | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}" | sort | uniq -c | sort -rn | head -10 | while read -r count date; do
    echo "- ${date}: ${count} entries"
done)

### Recent Additions (Last 30 Days)

$(grep "Added:" "$AGENTS_FILE" | grep -E "$(date -v-30d +%Y-%m-%d 2>/dev/null || date -d '30 days ago' +%Y-%m-%d)" | head -5 | sed 's/^/  - /' || echo "  (None in last 30 days)")

---

## Recommendations

### 1. Review Frequency

**Current Status**: Review generated on ${CURRENT_DATE}

**Recommendation**: 
- Review agents.md monthly for active projects
- Review quarterly for maintenance mode
- Review after major milestones

**Next Review**: $(date -v+30d +%Y-%m-%d 2>/dev/null || date -d '30 days' +%Y-%m-%d)

### 2. Content Quality

**Entries with Dates**: ${ENTRIES_WITH_DATES} / ${LEARNING_COUNT}

$(if [ "$ENTRIES_WITH_DATES" -lt "$LEARNING_COUNT" ]; then
    echo "⚠️  Some entries are missing dates. Consider adding dates to all entries."
else
    echo "✅ All entries have dates."
fi)

### 3. Organization

**Categories Found**:
- Architecture Principles: ${ARCHITECTURE_COUNT}
- Common Mistakes: ${MISTAKES_COUNT}
- Code Standards: ${STANDARDS_COUNT}

**Recommendation**: Ensure entries are properly categorized for easy reference.

---

## Patterns Detected

### Most Common Patterns

$(grep -E "^##|^###" "$AGENTS_FILE" | head -20 | sed 's/^/  - /')

---

## Action Items

- [ ] Review all entries for accuracy and relevance
- [ ] Archive outdated entries (older than 1 year if unused)
- [ ] Add examples to vague entries
- [ ] Merge duplicate entries if found
- [ ] Update "Last Updated" date in agents.md

---

## Next Steps

1. **Review this report** for insights
2. **Update agents.md** based on findings
3. **Run consistency checks** on related files
4. **Schedule next review** in 30 days

---

## Regeneration

To regenerate this report:

\`\`\`bash
bash .cursor/scripts/generate-agents-review.sh
\`\`\`

---

**Report Generated**: ${CURRENT_DATE}  
**Generated By**: agents.md review script
EOF

echo -e "${GREEN}✅ Review report generated${NC}"
echo ""
echo -e "${BLUE}📄 Report: ${REVIEW_FILE}${NC}"
echo ""
echo -e "${BLUE}Summary:${NC}"
echo "  Total Learnings: ${LEARNING_COUNT}"
echo "  Architecture Principles: ${ARCHITECTURE_COUNT}"
echo "  Common Mistakes: ${MISTAKES_COUNT}"
echo "  Code Standards: ${STANDARDS_COUNT}"
echo ""
echo -e "${YELLOW}💡 Review the report and update agents.md as needed${NC}"
